type Call = {
    callresolutionid: `callresolution:${string}:${string}`;
    callstatusid: string;
    calltypeid: `calltype:${string}:${string}`;
    contractid: `contract:${string}:${string}`;
    createdby: `${string}:${string}:${string}`;
    createdon: string;
    customerid: `customer:${string}:${string}`;
    dateofcall: string;
    description: string;
    division: string;
    employeeid: `employee:${string}:${string}`;
    estimatehours: number;
    gpcalltype: string;
    gpcustomernumber: string;
    gplocationnumber: string;
    gpproblemtype: string;
    gpservicecallid: string;
    gptechnicianid: string;
    id: string;
    invoicetype: number;
    isinternal: "False" | "True";
    locationid: `location:${string}:${string}`;
    modifiedby: `${string}:${string}:${string}`;
    modifiedon: string;
    name: string;
    primarytechemployeeid: `employee:${string}:${string}`;
    purchaseorder: string;
    salesperson: string;
    statecode: number;
    statuscode: number;
    versionnumber: number;
};
