type LocationData = {
    address1: string;
    affiliate: string;
    branch: string;
    city: string;
    createdby: `${string}:${string}:${string}`;
    createdon: string;
    customerid: `customer:${string}:${string}`;
    gpcustomernumber: string;
    gplocationnumber: string;
    id: string;
    isbillonly: "False" | "True";
    isinactive: "False" | "True";
    isservicelocation: "True" | "False";
    laborgroup: string;
    latitude: number;
    locationname: string;
    longitude: number;
    modifiedby: `${string}:${string}:${string}`;
    modifiedon: string;
    name: string;
    pricingmatrix: string;
    purchaseorderrequired: "True" | "False";
    region: string;
    salespersonnumber: string;
    state: string;
    statecode: number;
    statuscode: number;
    versionnumber: number;
    zip: number;
};
